# Generated by Django 6.1.1 on 2026-09-19 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Placed', 'Placed'), ('Confirmed', 'Confirmed'), ('Accepted', 'Accepted'), ('Preparing', 'Preparing'), ('Picked Up', 'Picked Up'), ('Ready', 'Ready'), ('Ready for Pickup', 'Ready for Pickup'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Collected', 'Collected'), ('Cancelled', 'Cancelled')], default='Placed', max_length=30),
        ),
    ]
